// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_session from "./routes/api/session.ts";
import * as $index from "./routes/index.tsx";
import * as $Index from "./islands/Index.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/session.ts": $api_session,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Index.tsx": $Index,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
